// <auto-generated />
using FilmApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilmApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210511205450_initialMigration2")]
    partial class initialMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("FilmApi.Models.FilmResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("genre_ids")
                        .HasColumnType("longtext");

                    b.Property<string>("original_title")
                        .HasColumnType("longtext");

                    b.Property<string>("overview")
                        .HasColumnType("longtext");

                    b.Property<string>("poster_path")
                        .HasColumnType("longtext");

                    b.Property<string>("release_date")
                        .HasColumnType("longtext");

                    b.Property<float>("vote_average")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
